# Generated by Django 3.2.9 on 2021-11-24 02:10

import crm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Fisrt Name')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=250)),
                ('address1', models.CharField(blank=True, max_length=1000, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=1000, verbose_name='Address line 2')),
                ('city', models.CharField(blank=True, max_length=1000, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=15, verbose_name='State')),
                ('zip_code', models.CharField(blank=True, max_length=15, verbose_name='Zip Code')),
                ('profile_picture', models.ImageField(blank=True, upload_to=crm.models.get_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
