# Generated by Django 3.2.9 on 2021-11-25 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField(verbose_name='Time Sent')),
                ('address1', models.CharField(blank=True, max_length=1000, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=1000, verbose_name='Address line 2')),
                ('city', models.CharField(blank=True, max_length=1000, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=15, verbose_name='State')),
                ('zip_code', models.CharField(blank=True, max_length=15, verbose_name='Zip Code')),
                ('contact', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='postcard', to='crm.contact')),
            ],
        ),
    ]
