# Generated by Django 3.2.9 on 2021-11-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_postcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcard',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='city',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='state',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='zip_code',
        ),
    ]
